version: "3.9"
services:
  milvus:
    image: milvusdb/milvus:v2.2.10
    container_name: milvus
    ports:
      - "19530:19530"
      - "9091:9091"
    environment:
      MILVUS_ROOT_USER: root
      MILVUS_ROOT_PASSWORD: milvus
    volumes:
      - milvus_data:/var/lib/milvus
volumes:
  milvus_data: