version: "3.9"

services:
  oracle23ai:
    image: gvenzl/oracle-free:23-slim
    container_name: oracle23ai
    ports:
      - "1521:1521"
    environment:
      APP_USER: mlops
      APP_USER_PASSWORD: mlops
    restart: "no" # équivalent à --rm (pas de redémarrage automatique)